'use client';

import React from 'react';
import { motion, Variants } from 'motion/react';

const fadeInUp: Variants = {
  initial: { opacity: 0, y: 30 },
  animate: { opacity: 1, y: 0, transition: { duration: 0.8, ease: 'easeOut' } }
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen pt-32 pb-24 px-6 max-w-3xl mx-auto w-full">
      <motion.div initial="initial" animate="animate" variants={fadeInUp}>
        <div className="mb-12">
          <h1 className="text-4xl md:text-5xl font-bold tracking-tight text-gray-900 mb-4">Terms of Service</h1>
          <p className="text-gray-500 font-medium">Last updated: May 13, 2026</p>
        </div>

        <div className="space-y-8 text-gray-600 leading-relaxed text-[15px]">
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-4">1. Agreement to Terms</h2>
            <p>By accessing or using Codera's fleet management software, hardware devices, and APIs (collectively, the "Services"), you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you do not have permission to access the Service.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-4">2. Hardware Liability</h2>
            <p>Codera provides telematics hardware "as-is". While our hardware is extensively tested, we are not liable for any mechanical failures, vehicle damage, or electrical faults that occur concurrently with the installation or operation of our OBD-II or hardwired units. Installation by a certified professional is highly recommended.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-4">3. Data Ownership & Usage</h2>
            <p>You retain full ownership of all GPS, telemetry, and camera data generated by your fleet. By using our Services, you grant Codera a non-exclusive license to process, store, and utilize this data strictly for the purpose of providing the Services to you, and to aggregate anonymized data for system improvements.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-4">4. Subscription and Billing</h2>
            <p>Services are billed on a subscription basis. You will be billed in advance on a recurring, periodic basis. Your subscription will automatically renew under the exact same conditions unless you cancel it or Codera cancels it.</p>
          </section>
        </div>
      </motion.div>
    </div>
  );
}

